# --- kak-lsp
eval %sh{kak-lsp --kakoune -s $kak_session}

hook global WinSetOption filetype=(nix|haskell) %{
    lsp-enable-window
}

hook global WinSetOption filetype=rust %{
    lsp-enable-window
    hook window BufWritePre .* lsp-formatting-sync
    hook  window -group rust-inlay-hints BufWritePost .* rust-analyzer-inlay-hints
    hook -once -always window WinSetOption filetype=.* %{
      remove-hooks window rust-inlay-hints
    }
}

# --- kakoune-rainbow
hook global ModuleLoaded rainbow %{
  set-option global rainbow_colors rgb:5E81AC+db rgb:BF616A+db rgb:D08770+db rgb:EBCB8B+db rgb:A3BE8C+db rgb:B48EAD+db
  hook global WinSetOption filetype=(rust|python|c|cpp|scheme|lisp|clojure|javascript|json|kak|haskell|python|latex|nix) %{
    rainbow-enable-window
  }
}

# --- Map
map global normal <c-f> ':fzf-mode<ret>v<ret>'


require-module rainbow
