# --- kks
eval %sh{ kks init }

# --- kak-lsp
eval %sh{kak-lsp --kakoune -s $kak_session}

hook global WinSetOption filetype=(nix|haskell) %{
    lsp-enable-window
}

hook global WinSetOption filetype=rust %{
    lsp-enable-window
    hook window BufWritePre .* lsp-formatting-sync
    hook  window -group rust-inlay-hints BufWritePost .* rust-analyzer-inlay-hints
    hook -once -always window WinSetOption filetype=.* %{
      remove-hooks window rust-inlay-hints
    }
}

# --- kakoune-rainbow
hook global ModuleLoaded rainbow %{
    set-option global rainbow_colors rgb:FF0000+db rgb:FF7F00+db rgb:FFFF00+db rgb:00FF00+db rgb:0000FF+db rgb:6A0DAD+db
    hook global WinSetOption filetype=(rust|python|c|cpp|scheme|lisp|clojure|javascript|json|kak|haskell|python|latex|nix) %{
        rainbow-enable-window
  }
}

# --- alacritty.kak
hook global ModuleLoaded x11 %{
    alias global terminal alacritty-terminal
    alias global popup alacritty-terminal-popup
}

# kakship-enable

# --- Map
map global normal <c-f> ':fzf-mode<ret>v<ret>'
map global normal <c-space> ':require-module rainbow<ret>:rainbow-enable-window<ret>'


require-module alacritty
